# Generated by Django 5.2.8 on 2025-11-21 22:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_play_song', models.BooleanField(default=True, verbose_name='Can play song')),
                ('can_create_playlist', models.BooleanField(default=True, verbose_name='Can create playlist')),
                ('can_play_playlist', models.BooleanField(default=True, verbose_name='Can play playlist')),
                ('can_download', models.BooleanField(default=True, verbose_name='Can download')),
                ('can_login', models.BooleanField(default=True, verbose_name='Can login')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='user_app_us_created_dc1a56_idx')],
            },
        ),
    ]
